### ISSUE TITLE
No X on Views and Editors

### ISSUE THREAD

**Issue by kferrone** [PyvesB/eclipse-planet-themes#7]
I have newest 2021-06 on the latest MacOS version. When planet-themes is installed and activated, the `X` button on the top right of all views editors tab disappears. Then I must right click and select close on editors and views to close them. It's real bad on some views with embedded tabs because they don't have the option to right click and close, for example the terminal view.

**Comment by PyvesB** [comment]
Hello @kferrone ! 👋🏻 

One of the goals of these themes is to maximise the space available to the user, removing the `x` buttons is very much by design.

These buttons are superfluous as tabs can be closed in so many other ways already:
* use the standard close tab keyboard shortcut.
* click anywhere on the tab header with the middle mouse button.
* select the close part action from the find actions menu.
* right click on the tab header and select the close entry in the menu.

Regarding the Terminal view, I feel that it's a missing piece of functionality there. The middle mouse button does work as expected, but there really should be a close terminal tab action, which would allow all the aforementioned alternatives. Another user has already reported this problem [here](https://bugs.eclipse.org/bugs/show_bug.cgi?id=462428), feel free to vote for the bug or add a comment so that it gets more traction. 😉

**Comment by kferrone** [comment]
I see, I kinda figured it was by design and I actually like it too. It was the terminal view which made me want to post this issue. A few times now I had a many terminal views open but when they get terminated, I can't close them . . . 
Oh well, it's fine.
